<a href="https://colab.research.google.com/github/marctnis/Redeneuralnumpy/blob/main/Redeneural.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
pip install numpy

In [7]:
pip install kagglehub

In [9]:
pip install tdqm

  Preparing metadata (setup.py) ... done
  Created wheel for tdqm: filename=tdqm-0.0.1-py3-none-any.whl size=1384 sha256=219f248a1407cd4b741fc3602a9f0208b10490f9c0083c3a40ec76e617414648
  Stored in directory: /root/.cache/pip/wheels/9a/91/f3/44d4e5da089935024002c5351f851f6f96e3ffa76995154241
Successfully built tdqm


In [10]:
import os
import numpy as np
from PIL import Image
import kagglehub
from tqdm import tqdm


In [11]:
path = kagglehub.dataset_download("olafkrastovski/handwritten-digits-0-9")

lista_imagens = []
lista_rotulos = []

pastas = [p for p in os.listdir(path) if os.path.isdir(os.path.join(path, p))]

for pasta_digito in tqdm(pastas, desc="Processando pastas (0-9)"):
    caminho_pasta = os.path.join(path, pasta_digito)

    for nome_arquivo in os.listdir(caminho_pasta):
        caminho_imagem = os.path.join(caminho_pasta, nome_arquivo)

        try:
            img = Image.open(caminho_imagem)
            lista_imagens.append(np.array(img))
            lista_rotulos.append(int(pasta_digito))
        except Exception:
            continue

X = np.array(lista_imagens, dtype=object)
y = np.array(lista_rotulos)

print(f"\nCarregamento concluído!")

Using Colab cache for faster access to the 'handwritten-digits-0-9' dataset.


Processando pastas (0-9): 100%|██████████| 10/10 [01:38<00:00,  9.89s/it]



Carregamento concluído!


In [12]:
print(X)

[[[[252 252 252]
   [253 253 253]
   [254 254 254]
   ...
   [255 255 255]
   [239 239 239]
   [217 217 217]]

  [[254 254 254]
   [254 254 254]
   [254 254 254]
   ...
   [253 253 253]
   [255 255 255]
   [242 242 242]]

  [[254 254 254]
   [254 254 254]
   [254 254 254]
   ...
   [251 251 251]
   [252 252 252]
   [246 246 246]]

  ...

  [[252 252 252]
   [253 253 253]
   [254 254 254]
   ...
   [252 252 252]
   [249 249 249]
   [247 247 247]]

  [[253 253 253]
   [253 253 253]
   [254 254 254]
   ...
   [252 252 252]
   [249 249 249]
   [248 248 248]]

  [[253 253 253]
   [253 253 253]
   [254 254 254]
   ...
   [252 252 252]
   [250 250 250]
   [249 249 249]]]


 [[[245 245 245]
   [255 255 255]
   [250 250 250]
   ...
   [248 248 248]
   [252 252 252]
   [251 251 251]]

  [[247 247 247]
   [255 255 255]
   [251 251 251]
   ...
   [251 251 251]
   [251 251 251]
   [248 248 248]]

  [[249 249 249]
   [254 254 254]
   [250 250 250]
   ...
   [254 254 254]
   [253 253 253]
   [249 249